-- 주석
-- 대소문자를 구별하지 않는다.
-- 일반적으로 오라클은 대문자로 작업하는 경우가 많다.
SELECT * FROM EMPLOYEES;

-- SELECT를 사용하여 EMPLOYEES테이블의 FIRST_NAME 컬럼만 선택하여 조회해보자.

SELECT FIRST_NAME 
FROM HR.EMPLOYEES;

-- SELECT를 사용하여 EMPLOYEES테이블의 FIRST_NAME 과 LAST_NAME컬럼을 선택하여 조회해보자.
SELECT FIRST_NAME, LAST_NAME  
FROM HR.EMPLOYEES;

-- 실습
-- 직원의 성, 이름, 휴대전화번호, 이메일주소, 사원번호를 한번에 조회하기
-- 순서대로 조회되어야 함.
SELECT FIRST_NAME, LAST_NAME,
	PHONE_NUMBER, EMAIL,
	EMPLOYEE_ID 
FROM HR.EMPLOYEES;


-- 정렬해서 조회하기
-- ORDER BY 절
-- 사원의 이름, 성, 봉급을 낮은 순서부터 조회(오름차순)
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY ASC; --오름차순

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC; --내림차순

-- 직원의 이름 성 고용일을 고용일 순서로 정렬

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

-- 직원의 이름 성 고용일을 고용일 순서로 정렬

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC;

-- 조회한 컬럼이 아니라도 정렬에 이용할수 있다.
SELECT FIRST_NAME, LAST_NAME 
FROM EMPLOYEES
ORDER BY SALARY;

-- 중복 제거
SELECT DISTINCT JOB_ID 
FROM EMPLOYEES;

SELECT DISTINCT JOB_ID, HIRE_DATE
FROM EMPLOYEES;

SELECT JOB_ID ,COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(*)
FROM
   (SELECT DISTINCT JOB_ID, HIRE_DATE
   FROM EMPLOYEES)
GROUP BY JOB_ID;

SELECT DISTINCT JOB_ID, HIRE_DATE 
FROM EMPLOYEES;

-- 별칭부여하기, 별명붙이기
-- AS 생략가능
-- "" 생략가능
-- 컬럼에 부여된 별명으로 정렬도 가능하다.
SELECT FIRST_NAME AS "이름", --ALIAS알리아스
	LAST_NAME AS "성",
	SALARY AS "봉급",
	EMPLOYEE_ID AS "사원번호"
FROM EMPLOYEES
ORDER BY 봉급, FIRST_NAME DESC, 3;

-- SELECT 절에서 조회하는 컬럼의 순서에 맞게 번호가 매겨진다.
SELECT FIRST_NAME, SALARY , HIRE_DATE 
FROM EMPLOYEES
ORDER BY SALARY, FIRST_NAME DESC, 3; -- SELECT 절의 숫자로 매길수 있음

